stages:
  - setup
  - plan
  - apply

variables:
  TF_VERSION: "1.0.0"

before_script:
  - apk add --update --no-cache curl jq unzip
  - |
    # Install Terraform
    curl -LO "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
    unzip "terraform_${TF_VERSION}_linux_amd64.zip"
    chmod +x terraform
    mv terraform /usr/local/bin/

setup:
  stage: setup
  script:
    - terraform --version

plan:
  stage: plan
  script:
    - terraform init
    - terraform validate
    - terraform plan -out=tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
